### ISSUE TITLE
Support more BaseDNs

### ISSUE THREAD

**Issue by kepi** [kamax-matrix/mxisd#104]
It would be great to be able to set more than one *BaseDN*. 

Currently, format is:

```
ldap.connection.baseDn: 'OU=interns,DC=example,DC=org'
```

We could use i.e. semicolon (at least that is the way same thing is specified in Seafile) to specify more:

```
ldap.connection.baseDn: 'OU=interns,DC=example,DC=org;OU=externs,DC=example,DC=org'
```

This is useful in cases where you can't set common parent, i.e. when there are more OUs on same level and you only want to access for some of them.

**Comment by maxidor** [comment]
@kepi Available in [v1.2.2](https://github.com/kamax-matrix/mxisd/releases/tag/v1.2.2)
