### ISSUE TITLE
SQL Backend Not Documented

### ISSUE THREAD

**Issue by palmtown** [kamax-matrix/mxisd#107]
The SQL documentation on https://github.com/kamax-matrix/mxisd/blob/master/docs/stores/sql.md is not completed.  It shows information for directory,  but does not show what it is expecting for Identity and Profile.  Therefore, can not determine what to query or return from sql.

**Comment by palmtown** [comment]
Thanks for the prompt response, I'll use the REST API in the interim, however, it is much more efficient, faster and redundant by using SQL.  Reason being is that one doesn't have to configure a web server to accept query, wait for web server to process query or if web server goes down can take down all of the queries.  

You can imagine how much faster results will be if searching database directly.  Look forward to the updated doc.

**Comment by maxidorius** [comment]
This will be done as part of the v1.4 release, since it will heavily feature SQL-based backend.
