### ISSUE TITLE
Add Requesting User ID to Backend Queries/API Request

### ISSUE THREAD

**Issue by palmtown** [kamax-matrix/mxisd#108]
This is a feature request.

When searching via SQL or REST API, make the requesting user ID available.  This is to prevent users from being returned that selects not to be found by certain users.

**Comment by maxidor** [comment]
Good idea; be aware that this would only available for the Directory feature, which is the only endpoint which requires an access token to be provided. Anything regarding Identity and Profile do not need such info and therefore never sent by the client.

**Comment by palmtown** [comment]
Thanks for your response, even if Directory only, that is a great start.  This would allow one to block users from being found in a wide away of cases.  Some may only want to be found by members of their own organization/domain etc vs by the entire world.

**Comment by maxidorius** [comment]
This project is no longer maintained.
