### ISSUE TITLE
Incorrect REST API URL for single and bulk default paths

### ISSUE THREAD

**Issue by palmtown** [kamax-matrix/mxisd#110]
In doc https://github.com/kamax-matrix/mxisd/blob/master/docs/stores/rest.md, it states that the default path for rest.endpoints.identity.single is /_mxisd/backend/api/v1/identity/single, however, when I checked on the server it is trying to access _mxisd/backend/api/v1/identity/lookup/single.  This is the same for bulk.

**Comment by maxidor** [comment]
Good catch! Will fix the docs

**Comment by maxidor** [comment]
To remain consistent with the rest, we actually made the default config to align with the docs. Fix will be present in the next release. For now, manually set the right config.
