### ISSUE TITLE
Can I/Should I install Mxisd server on the same machine as Synapse?

### ISSUE THREAD

**Issue by PiotrIr** [kamax-matrix/mxisd#114]
Hi,
I just wander, should I install Mxisd on the same server where Synapse is running or it should be dedicated machine? Any disadvantages/advantages of both configuration which I should know? What about database? I'm using PostgreSQL, do I need to install MySQL on top of this if they are on the same server?

**Comment by maxidorius** [comment]
There is no recommendation at the level of installing it (or not) on the same host as synapse. The recommendation we have is to have dedicated host(s) for Matrix stuff (or use docker contains) so you can easily deal with requirements of HS/IS hostnames and in general have everything under a matrix subdomain while using SRV records to use a nice vanity domain in your IDs.

mxisd database is a single SQLite file very rarely accessed on a typical platform (or not even at all) with non-critical data (but still important). MySQL is not something mxisd uses.

**Comment by PiotrIr** [comment]
Thank you Max, I have dedicated host for Matrix so will install mxisd on the same.
