### ISSUE TITLE
LDAP Identity store - dead link in documentation

### ISSUE THREAD

**Issue by tgurr** [kamax-matrix/mxisd#136]
In https://github.com/kamax-matrix/mxisd/blob/master/docs/stores/ldap.md the `"default list of attributes"` link leads to https://github.com/kamax-matrix/mxisd/blob/master/src/main/resources/application.yaml#L67 which doesn't seem to exist anymore.

**Comment by maxidorius** [comment]
You're right, thank you for pointing it out! There is no equivalent in v1.3 so I'll see how I can fix that...
