### ISSUE TITLE
Follow LDAP referrals

### ISSUE THREAD

**Issue by maxidorius** [kamax-matrix/mxisd#14]
Current code does not follow LDAP referrals for simplicity.

This issue represent the work to implement such support, including an config parameter to enable referrals follow or not.

**Comment by maxidor** [comment]
At this point, there is no maintained LDAP library out there that nicely handles referrals, so this is stuck.

**Comment by maxidor** [comment]
Since a better LDAP library is required for v2.x, this will be made as part of that work.

**Comment by maxidorius** [comment]
Re-opening this issue as there might be a way around the current limitations using the [Exec Identity store](https://github.com/kamax-matrix/mxisd/blob/master/docs/stores/exec.md) with the `ldap` cli tools.

**Comment by maxidorius** [comment]
While `ldapsearch` can follow referrals, it does so anonymously without binding first which is totally unhelpful on our case. So we're kinda back to square 1 where we need to find a way to follow referrals.

Need to investigate if there are better CLI tools out there.

**Comment by maxidorius** [comment]
This seems to only happen with AD users (so far). Next plan is to do a SVC lookup and see if we can find a DC that could give us the info.

**Comment by maxidorius** [comment]
So far not much luck. The testing environment we had access to (but no longer) only seemed to send referrals for a given account, which feels like it was either misconfigured or referrals are totally misunderstood on our end. Marking as blocking again until further work can be done.

Research code has been commited to a dedicated branch for now.

**Comment by maxidorius** [comment]
This project is no longer maintained.
