### ISSUE TITLE
Feature Request - Nested groups in LDAP filters

### ISSUE THREAD

**Issue by jkms** [kamax-matrix/mxisd#147]
Please allow the possibility of using nested groups in conjunction with LDAP filters.  At this time, each user must a direct member of the group defined in the filter.  It would be very helpful for to use nested groups in order to alleviate an automate Matrix/MXISD permissions.

Thanks in advance!

**Comment by maxidorius** [comment]
@jkms To be sure I do not forget (again) what you're expecting in terms of configuration/behaviour, could you give an example of how you envision the configuration to be for this?

**Comment by jkms** [comment]
Sorry for the late response (vacation).

My case would look like this:

**User A** (user):
- memberOf:
  - **Developers** (group)

**Developers** (group):
- memberOf:
  - Git_Users (group)
  - **Matrix_Users** (group)
  - Mail_Users (group)
  - etc...

The idea being that a user is placed into a group, and inherits permissions for the systems that they need.  In the example above, **User A** is a developer, and is in the **Developer** group.  The **Developer** group is itself in a number of groups, and those groups grant permissions to various systems.

With the current LDAP implementation of MXISD, I need to manually enter users directly into the **Developers** Group, which is much more difficult to maintain.

**Comment by maxidorius** [comment]
This project is no longer maintained.
