### ISSUE TITLE
Internal Bind API

### ISSUE THREAD

**Issue by zatsepinvl** [kamax-matrix/mxisd#149]
Is there API like https://github.com/matrix-org/sydent#internal-bind-api?

**Comment by maxidorius** [comment]
As explained in the [concepts](https://github.com/kamax-matrix/mxisd/blob/master/docs/concepts.md#identity-store) documents, under `mxisd > Identity stores`, mxisd itself doesn't store bindings, or 3PIDs, nor does it write to Identity stores.

This API therefore doesn't exist in mxisd as it doesn't make sense for it. If you want to add 3PID mappings, add the relevant information in your Identity store(s) and mxisd will pick it up automatically.
