### ISSUE TITLE
registration option throught mxisd and Appache

### ISSUE THREAD

**Issue by Unsourire** [kamax-matrix/mxisd#157]
Hello,
i wanted to integrate the registration option throught the mxisd but how can i configure my reverse proxy on Appache? Is it fine to have only this line : 
ProxyPass /_matrix/client/r0/register/ http://localhost:8090 ?
it seems to not working!
Thank in adavnce for your help

**Comment by maxidorius** [comment]
> integrate the registration option

Keep in mind that it is only available in the alpha release which is not complete yet

> Is it fine to have only this line : `ProxyPass /_matrix/client/r0/register/ http://localhost:8090 ?`

No, you'll need to translate what is [currently documented for nginx](https://github.com/kamax-matrix/mxisd/blob/master/docs/features/registration.md#nginx), apache doc is not available yet.
