### ISSUE TITLE
default email templates 

### ISSUE THREAD

**Issue by fredhampton** [kamax-matrix/mxisd#162]
In what directory are the default email templates ?

Thanks !

**Comment by maxidorius** [comment]
They are built-in. If you would like to change them, the sources are available [here](https://github.com/kamax-matrix/mxisd/tree/master/src/main/resources/threepids)

**Comment by fredhampton** [comment]
Is there a way to make the changes without having to rebuild from source ?


Thanks !

**Comment by maxidorius** [comment]
See [here](https://github.com/kamax-matrix/mxisd/blob/master/docs/threepids/notification/template-generator.md#notifications-generate-from-templates). You should read the docs fully also, all your open issues are answered one way or another in them.
