### ISSUE TITLE
Unable to remove contact information Failed to remove threepid

### ISSUE THREAD

**Issue by fredhampton** [kamax-matrix/mxisd#163]
Add an email to the users settings.
Tried to delete the email using the U.I. in settings by clicking on the X
Received the following error message 
"Unable to remove contact information
Failed to remove threepid"

Thanks !

**Comment by maxidorius** [comment]
Please read [this wiki page](https://github.com/kamax-matrix/mxisd/wiki/mxisd-and-your-privacy#mxisd-and-your-privacy).
