### ISSUE TITLE
Error when adding a phone number to members profile 

### ISSUE THREAD

**Issue by fredhampton** [kamax-matrix/mxisd#164]
When adding a phone number to a members profile via settings U.I. I receive the following error message 

msisdn is not a supported 3PID medium type (Status 501)

Thanks !

**Comment by maxidorius** [comment]
You did not configure a way for mxisd to send SMS, and thus can't validate phone numbers. Only [Twilio](https://github.com/kamax-matrix/mxisd/blob/master/docs/threepids/medium/msisdn/twilio-connector.md) is supported at this time.

Phone numbers have no use in Matrix at this time, as no client support using them for lookup or any other kind of interaction other than adding them. They are also not made visible.

**Comment by fredhampton** [comment]
Thank you so much for your help !!!!!
Do you know if there is a way to not show the phone number option anywhere on a client ?

**Comment by maxidorius** [comment]
I'm not aware of any such option. You'll need to ask the client's developers. I'll close the issue now. Feel free to re-open if you feel it hasn't been answered.
