### ISSUE TITLE
Key path in config / no key generation

### ISSUE THREAD

**Issue by menturion** [kamax-matrix/mxisd#166]
I am currently trying to set up your identity server (v1.3.1) and stuck.
Your Getting Started doc (https://github.com/kamax-matrix/mxisd/blob/master/docs/getting-started.md) says that ...

`key.path will store the signing keys, which must be kept safe! If the file does not exist, keys will be generated for you.`

However, when I just set the path to a folder your config checker throws an error on startup, saying ...

`"Signing key file storage "pathtofolder" is a directory".`

The key file does not exist.

**Question:**
How can I generate the signing key(s)?

**Comment by menturion** [comment]
Got it.
Had to add a folder path to a key that does not exist. For all who might stumble upon the same problem:

So instead of referencing an empty key folder like this ...

`'[pathtofolder]/keys/'`

one has to reference a key that does not exist, e.g. like this ...

`'[pathtofolder]/keys/signing.key'`

Then `'signing.key'` will be generated on startup.

**Comment by maxidorius** [comment]
This is expected. The documentation specifically says "file", not "directory". If the path given points to a directory, then a file located at that path cannot be created, as it's already taken by a directory.

**Comment by menturion** [comment]
Once again thanks for your help!
