### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by fredhampton** [kamax-matrix/mxisd#168]
Is it possible to have mxisd send specific email notifications that are triggered by users turning on Enable email notifications in settings ?

**Comment by maxidorius** [comment]
See my reply [here](https://matrix.to/#/!NPRUEisLjcaMtHIzDr:kamax.io/$155624455014518wMeGZ:kamax.io?via=kamax.io&via=matrix.org&via=chat.weho.st)
