### ISSUE TITLE
Email verification with wrong link

### ISSUE THREAD

**Issue by smoebody** [kamax-matrix/mxisd#176]
When i register at my own hosted server the verification-email is wrong since synapse runs on a subdomain e.g. `matrix.example.com` and the url points to `example.com`. 
I have a `.well-known`-entry at `example.com/.well-known/_matrix/server` and `example.com/.well-known/_matrix/client` which state each server-host but they seem unconsidered.

**Comment by maxidorius** [comment]
You have at your disposal two configuration variables to adapt this behaviour:
- `server.name` as described in the [Getting Started](https://github.com/kamax-matrix/mxisd/blob/master/docs/getting-started.md#configure) and the [Configuration](https://github.com/kamax-matrix/mxisd/blob/master/docs/configure.md#configuration) documentation.
- `REGISTER_URL` placeholder for the [invite notification template](https://github.com/kamax-matrix/mxisd/blob/master/docs/threepids/notification/template-generator.md#notifications-template-generator).

You may need to use both depending on your setup.

**Comment by smoebody** [comment]
Ah thanks. Somehow i missed that `server.name` option.
