### ISSUE TITLE
Key with ID ed25519:0 does not exist

### ISSUE THREAD

**Issue by biolim** [kamax-matrix/mxisd#178]
CentOS Linux release 7.6.1810 (Core)
Kamax-matrix/mxisd - 1.4.4
OpenJDK-1.8

` #curl http://localhost:8090/_matrix/identity/api/v1/pubkey/ed25519:0
{"errcode":"M_NOT_FOUND","error":"Key with ID ed25519:0 does not exist","success":false}`

`#cat /etc/mxisd/mxisd.yaml`
`...
key:
  path: '/var/lib/mxisd/keys'
...`

`#ls /var/lib/mxisd/keys
current  regular`

`#tail /var/log/messages`
`Jun  3 06:34:20 matrix01 mxisd: [XNIO-1 task-4] INFO io.kamax.mxisd.http.undertow.handler.identity.v1.KeyGetHandler - Key ed25519:0 was requested
Jun  3 06:34:20 matrix01 mxisd: [XNIO-1 task-4] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request GET http://localhost:8090/_matrix/identity/api/v1/pubkey/ed25519:0 - Error M_NOT_FOUND: Key with ID ed25519:0 does not exist`

**Comment by maxidorius** [comment]
I think there isn't an issue here, the key ID provided just doesn't exist.
The content of the `current` file in `/var/lib/mxisd/keys` would tell you what the identifier values are.

**Comment by biolim** [comment]
`cat current
{"type":"Regular","algo":"ed25519","serial":"AAAAAwbparUn"}`

**Comment by maxidorius** [comment]
Then the right URL would be
```
http://localhost:8090/_matrix/identity/api/v1/pubkey/ed25519:AAAAAwbparUn
```

**Comment by biolim** [comment]
Thanks. Works.
