### ISSUE TITLE
3pid unbind

### ISSUE THREAD

**Issue by wabuMike** [kamax-matrix/mxisd#184]
Since [MSC1915](https://github.com/matrix-org/matrix-doc/pull/2046) has now been added to spec, are the concerns expressed in [mxisd-and-your-privacy](https://github.com/kamax-matrix/mxisd/wiki/mxisd-and-your-privacy#improving-your-privacy-one-commit-at-the-time) still valid?

**Comment by wabuMike** [comment]
I'm asking, because in the logs there is this: `Error M_FORBIDDEN: 3PID can only be removed via 3PID sessions, not via Homeserver signature`.

**Comment by wabuMike** [comment]
Just found in your [release notes](https://github.com/kamax-matrix/mxisd/releases/tag/v1.4.5) that this should work. Am I missing anything else here? I'm running mxisd 1.4.5.

**Comment by maxidorius** [comment]
MSC1915 provides two ways to do a 3PID removal, and says the Identity Server can do it with either, without requiring both. This has been confirmed by Travis, a core team member.

Riot/synapse don't give you a choice in which to use - I can only suggest to open an issue on one of the repos, or on both, to offer both possibility to the user.
