### ISSUE TITLE
Group/Community integrations into Directory lookup and Invitations

### ISSUE THREAD

**Issue by maxidorius** [kamax-matrix/mxisd#50]
To fill the current gap with ***groups*** not being able to be used for invitations to rooms:
- Integrate ***groups*** when doing a search to perform invite, adding them to the [Directory](https://github.com/kamax-io/mxisd/blob/master/docs/features/directory-users.md) feature, possibly via a special namespace.
- Resolve those special/virtual users so ***groups*** invite can be turned into user invites.

At this point, ***groups*** means both Identity store groups (if supported) and native Matrix communities (with proper integration).

**Comment by maxidor** [comment]
Blocked on a stable group/community API

**Comment by maxidorius** [comment]
This project is no longer maintained.
