### ISSUE TITLE
Support user photo from LDAP

### ISSUE THREAD

**Issue by awesome-manuel** [kamax-matrix/mxisd#83]
LDAP can store user photos. Would be nice to automatically use those for matrix as well.

**Comment by maxidor** [comment]
In which feature would you want support for those exactly?

**Comment by awesome-manuel** [comment]
Auto-fill of user profile (Display name, 3PIDs) *+ user photo* for LDAP store.

**Comment by maxidor** [comment]
This will need to be implemented first in the [REST password provider] which is used to link synapse to mxisd. It wasn't done before due to lack of good API calls and privacy concerns. I can revisit this in the coming weeks and see if something can be done.

**Comment by maxidor** [comment]
Given the complexity of this extra feature, it will be worked as part of v2.x if and when it happens.
