### ISSUE TITLE
Better support for LDAP autofill and room autojoin

### ISSUE THREAD

**Issue by ananace** [kamax-matrix/mxisd#92]
Currently, when a new user logs in on a Synapse + MXISD combo - with the server configured to autojoin users to a room, then their joined presence will not be updated with the filled profile data.

If it's possible, could autofill also trigger a membership update if it adds a display name or avatar to a user profile? Or possibly just the first time it triggers for a new user?

**Comment by maxidor** [comment]
mxisd is not responsible for interacting with synapse, the [REST password provider is](https://github.com/kamax-matrix/matrix-synapse-rest-auth). mxisd simply validate credentials and provides the profile of the user.
