### ISSUE TITLE
How can I debug failing LDAP authentication?

### ISSUE THREAD

**Issue by rsacher** [kamax-matrix/mxisd#94]
On riot.im with existing ActiveDirectory username and password, I only get "Invalid Login Data"  (roughly translated from german "Ungültige Zugangsdaten"

How could I trace the problem ?

Snip of my mxisd config

```
ldap.enabled: true
ldap.connection.host: '10.0.0.111'
ldap.connection.port: 389
ldap.connection.bindDn: 'CN=ldapquery,CN=Users,DC=bgs,DC=ac,DC=at'
ldap.connection.bindPassword: '<password>'
ldap.connection.baseDn: 'DC=bgs,DC=ac,DC=at'
#- 'OU=moodle,OU=schuler,DC=bgs,DC=ac,DC=at'
#- 'OU=moodle,OU=schuler,DC=bgs,DC=ac,DC=at'

ldap.attribute.uid.type: 'uid'
ldap.attribute.uid.value: 'sAMAccountName'
ldap.attribute.name: 'displayName'
#ldap.attribute.threepid.email: 'mail'

ldap.directory.attribute.other:
  - 'sn'
  - 'memberOf'
  - 'givenName'

```
in my homeserver.yaml I have listed my identiy server, which is the same machine as matrix-server 

```

trusted_third_party_id_servers:
    - www.bgschwechat.ac.at
#    - matrix.org
#    - vector.im
#    - riot.im


```

**Comment by maxidor** [comment]
I'll need the mxisd logs about the login attempt - you can't really miss them. Make sure you post the whole section, not just the first/last line.

**Comment by rsacher** [comment]
Sorry, I really miss them  - thats why I was asking - where are logs for mxisd located on Ubuntu ..?

**Comment by maxidor** [comment]
If you installed via the .deb packages, they are in syslog. mxisd just write to stdout which is put to syslog on debian/ubuntu

**Comment by rsacher** [comment]
restarted mxisd and attempted a login, which failed... cannot see any notice of the attempt...
getting the impression, mxsid is not called at all...
am I  missing something in my homeserver.yaml.....?


Nov 10 19:49:29 www2018 systemd[1]: Stopping mxisd...
Nov 10 19:49:29 www2018 systemd[1]: Stopped mxisd.
Nov 10 19:49:29 www2018 systemd[1]: Started mxisd.
Nov 10 19:49:31 www2018 mxisd[6972]: .103  INFO [           main] k.m.MatrixIdentityServerApplication : Starting MatrixIdentityServerApplication on www2018 with PID 7003 (/usr/lib/mxisd/mxisd.jar started by mxisd in /usr/lib/mxisd)
Nov 10 19:49:31 www2018 mxisd[6972]: .107  INFO [           main] k.m.MatrixIdentityServerApplication : The following profiles are active: systemd
Nov 10 19:49:33 www2018 mxisd[6972]: .898  INFO [           main]       i.k.m.c.t.c.PhoneTwilioConfig : --- Phone SMS Twilio connector config ---
Nov 10 19:49:33 www2018 mxisd[6972]: .899  INFO [           main]       i.k.m.c.t.c.PhoneTwilioConfig : Account SID:
Nov 10 19:49:33 www2018 mxisd[6972]: .900  INFO [           main]       i.k.m.c.t.c.PhoneTwilioConfig : Sender number:
Nov 10 19:49:33 www2018 mxisd[6972]: .902  INFO [           main] i.k.m.t.c.p.PhoneSmsTwilioConnector : Twilio API has been initiated
Nov 10 19:49:33 www2018 mxisd[6972]: .930  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : --- E-mail SMTP Connector config ---
Nov 10 19:49:33 www2018 mxisd[6972]: .931  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Host: 10.0.0.118
Nov 10 19:49:33 www2018 mxisd[6972]: .931  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Port: 25
Nov 10 19:49:33 www2018 mxisd[6972]: .931  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : TLS Mode: 1
Nov 10 19:49:33 www2018 mxisd[6972]: .931  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Login: matrix@bgschwechat.ac.at
Nov 10 19:49:33 www2018 mxisd[6972]: .935  INFO [           main]         i.k.m.c.t.c.EmailSmtpConfig : Has password: true
Nov 10 19:49:33 www2018 mxisd[6972]: .972  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : --- Matrix config ---
Nov 10 19:49:33 www2018 mxisd[6972]: .972  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : Domain: wwww.bgschwechat.ac.at
Nov 10 19:49:33 www2018 mxisd[6972]: .972  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : Identity:
Nov 10 19:49:34 www2018 mxisd[6972]: .012  INFO [           main]  io.kamax.mxisd.config.MatrixConfig : #011Servers: {"matrix-org":["https://matrix.org"]}
Nov 10 19:49:34 www2018 mxisd[6972]: .029  INFO [           main]  io.kamax.mxisd.config.ServerConfig : --- Server config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .031  INFO [           main]  io.kamax.mxisd.config.ServerConfig : Name: wwww.bgschwechat.ac.at
Nov 10 19:49:34 www2018 mxisd[6972]: .031  INFO [           main]  io.kamax.mxisd.config.ServerConfig : Port: 8090
Nov 10 19:49:34 www2018 mxisd[6972]: .031  INFO [           main]  io.kamax.mxisd.config.ServerConfig : Public URL: https://wwww.bgschwechat.ac.at
Nov 10 19:49:34 www2018 mxisd[6972]: .072  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : --- Email SendGrid connector config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .074  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : API key configured?: false
Nov 10 19:49:34 www2018 mxisd[6972]: .077  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : Identity: {"from":"","name":""}
Nov 10 19:49:34 www2018 mxisd[6972]: .078  INFO [           main]     i.k.m.c.t.c.EmailSendGridConfig : Templates: {"invite":{"subject":"","body":{"text":"","html":""}},"session":{"local":{"body":{}},"remote":{"body":{}}}}
Nov 10 19:49:34 www2018 mxisd[6972]: .321  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : --- SMS Generator templates config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .322  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Invite: Built-in (threepids/sms/invite-template.txt)
Nov 10 19:49:34 www2018 mxisd[6972]: .322  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Session validation:
Nov 10 19:49:34 www2018 mxisd[6972]: .322  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : #011Local: Built-in (threepids/sms/validate-local-template.txt)
Nov 10 19:49:34 www2018 mxisd[6972]: .322  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : #011Remote: Built-in (threepids/sms/validate-remote-template.txt)
Nov 10 19:49:34 www2018 mxisd[6972]: .348  INFO [           main]        i.k.m.c.t.medium.PhoneConfig : --- Phone config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .349  INFO [           main]        i.k.m.c.t.medium.PhoneConfig : Generator: template
Nov 10 19:49:34 www2018 mxisd[6972]: .349  INFO [           main]        i.k.m.c.t.medium.PhoneConfig : Connector: twilio
Nov 10 19:49:34 www2018 mxisd[6972]: .385  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : --- E-mail Generator templates config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .385  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Invite: Built-in (threepids/email/invite-template.eml)
Nov 10 19:49:34 www2018 mxisd[6972]: .385  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : Session validation:
Nov 10 19:49:34 www2018 mxisd[6972]: .386  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : #011Local: Built-in (threepids/email/validate-local-template.eml)
Nov 10 19:49:34 www2018 mxisd[6972]: .386  INFO [           main]     i.k.m.c.t.m.EmailTemplateConfig : #011Remote: Built-in (threepids/email/validate-remote-template.eml)
Nov 10 19:49:34 www2018 mxisd[6972]: .410  INFO [           main]        i.k.m.c.t.medium.EmailConfig : --- E-mail config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .410  INFO [           main]        i.k.m.c.t.medium.EmailConfig : From: matrix@bgschwechat.ac.at
Nov 10 19:49:34 www2018 mxisd[6972]: .411  INFO [           main]        i.k.m.c.t.medium.EmailConfig : Name: Wwww.bgschwechat.ac.at Identity Server
Nov 10 19:49:34 www2018 mxisd[6972]: .411  INFO [           main]        i.k.m.c.t.medium.EmailConfig : Generator: template
Nov 10 19:49:34 www2018 mxisd[6972]: .411  INFO [           main]        i.k.m.c.t.medium.EmailConfig : Connector: smtp
Nov 10 19:49:34 www2018 mxisd[6972]: .453  INFO [           main]  i.kamax.mxisd.config.SessionConfig : --- Session config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .454  INFO [           main]  i.kamax.mxisd.config.SessionConfig : Global Policy: {"validation":{"enabled":true,"forLocal":{"enabled":true,"toLocal":true,"toRemote":{"enabled":true,"server":"matrix-org"}},"forRemote":{"enabled":true,"toLocal":false,"toRemote":{"enabled":true,"server":"matrix-org"}}}}
Nov 10 19:49:34 www2018 mxisd[6972]: .471  INFO [           main]      i.k.m.c.t.n.NotificationConfig : --- Notification config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .471  INFO [           main]      i.k.m.c.t.n.NotificationConfig : Handlers:
Nov 10 19:49:34 www2018 mxisd[6972]: .523  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : --- Generic SQL Provider config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .523  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : Enabled: false
Nov 10 19:49:34 www2018 mxisd[6972]: .545  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : --- Synapse SQL Provider config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .546  INFO [           main]  i.kamax.mxisd.config.sql.SqlConfig : Enabled: false
Nov 10 19:49:34 www2018 mxisd[6972]: .563  INFO [           main]      i.k.m.c.rest.RestBackendConfig : --- REST backend config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .563  INFO [           main]      i.k.m.c.rest.RestBackendConfig : Enabled: false
Nov 10 19:49:34 www2018 mxisd[6972]: .587  INFO [           main]    io.kamax.mxisd.config.ViewConfig : --- View config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .588  INFO [           main]    io.kamax.mxisd.config.ViewConfig : Session: {"local":{"onTokenSubmit":{"failure":"session/local/tokenSubmitFailure","success":"session/local/tokenSubmitSuccess"}},"localRemote":{"onTokenSubmit":{"failure":"session/local/tokenSubmitFailure","success":"session/localRemote/tokenSubmitSuccess"}},"remote":{"onRequest":{"failure":"session/remote/requestFailure","success":"session/remote/requestSuccess"},"onCheck":{"failure":"session/remote/checkFailure","success":"session/remote/checkSuccess"}}}
Nov 10 19:49:34 www2018 mxisd[6972]: .607  INFO [           main]   i.k.mxisd.config.InvitationConfig : --- Invite config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .608  INFO [           main]   i.k.mxisd.config.InvitationConfig : Resolution: {"recursive":true,"timer":1}
Nov 10 19:49:34 www2018 mxisd[6972]: .617  INFO [           main]     i.k.m.config.DnsOverwriteConfig : --- DNS Overwrite config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .617  INFO [           main]     i.k.m.config.DnsOverwriteConfig : Homeserver:
Nov 10 19:49:34 www2018 mxisd[6972]: .617  INFO [           main]     i.k.m.config.DnsOverwriteConfig : #011Client: []
Nov 10 19:49:34 www2018 mxisd[6972]: .618  INFO [           main]     i.k.m.config.DnsOverwriteConfig : #011Federation: []
Nov 10 19:49:34 www2018 mxisd[6972]: .628  INFO [           main]     i.k.mxisd.config.FirebaseConfig : --- Firebase configuration ---
Nov 10 19:49:34 www2018 mxisd[6972]: .628  INFO [           main]     i.k.mxisd.config.FirebaseConfig : Enabled: false
Nov 10 19:49:34 www2018 mxisd[6972]: .642  INFO [           main] i.k.m.c.RecursiveLookupBridgeConfig : --- Bridge integration lookups config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .643  INFO [           main] i.k.m.c.RecursiveLookupBridgeConfig : Enabled: false
Nov 10 19:49:34 www2018 mxisd[6972]: .683  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : --- Generic LDAP Config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .684  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Enabled: true
Nov 10 19:49:34 www2018 mxisd[6972]: .687  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Host: 10.0.0.111
Nov 10 19:49:34 www2018 mxisd[6972]: .687  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Port: 389
Nov 10 19:49:34 www2018 mxisd[6972]: .687  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : TLS: false
Nov 10 19:49:34 www2018 mxisd[6972]: .687  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Bind DN: CN=ldapquery,CN=Users,DC=bgs,DC=ac,DC=at
Nov 10 19:49:34 www2018 mxisd[6972]: .687  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Base DN: DC=bgs,DC=ac,DC=at
Nov 10 19:49:34 www2018 mxisd[6972]: .690  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Attribute: {"uid":{"type":"uid","value":"sAMAccountName"},"name":"displayName","threepid":{"msisdn":["telephoneNumber","mobile","homePhone","otherTelephone","otherMobile","otherHomePhone"],"email":["mailPrimaryAddress","mail","otherMailbox"]}}
Nov 10 19:49:34 www2018 mxisd[6972]: .691  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Auth: {"filter":""}
Nov 10 19:49:34 www2018 mxisd[6972]: .691  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Directory: {"attribute":{"other":["sn","memberOf","givenName"]},"filter":""}
Nov 10 19:49:34 www2018 mxisd[6972]: .691  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Identity: {"filter":"","token":"%3pid","medium":{"msisdn":"(|(telephoneNumber=+%3pid)(mobile=+%3pid)(homePhone=+%3pid)(otherTelephone=+%3pid)(otherMobile=+%3pid)(otherHomePhone=+%3pid))","email":"(|(mailPrimaryAddress=%3pid)(mail=%3pid)(otherMailbox=%3pid))"}}
Nov 10 19:49:34 www2018 mxisd[6972]: .716  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : --- NetIQ eDirectory Config ---
Nov 10 19:49:34 www2018 mxisd[6972]: .717  INFO [           main]    i.k.mxisd.config.ldap.LdapConfig : Enabled: false
Nov 10 19:49:34 www2018 mxisd[6972]: .829  INFO [g-Init-Reporter]             com.mchange.v2.log.MLog : MLog clients using slf4j logging.
Nov 10 19:49:34 www2018 mxisd[6972]: .867  INFO [           main]    com.mchange.v2.c3p0.C3P0Registry : Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
Nov 10 19:49:35 www2018 mxisd[6972]: .104  INFO [           main]         i.k.m.n.NotificationManager : Found handler sendgrid for medium email
Nov 10 19:49:35 www2018 mxisd[6972]: .105  INFO [           main]         i.k.m.n.NotificationManager : Found handler raw for medium msisdn
Nov 10 19:49:35 www2018 mxisd[6972]: .106  INFO [           main]         i.k.m.n.NotificationManager : Found handler raw for medium email
Nov 10 19:49:35 www2018 mxisd[6972]: .106  INFO [           main]         i.k.m.n.NotificationManager : --- Notification handler ---
Nov 10 19:49:35 www2018 mxisd[6972]: .107  INFO [           main]         i.k.m.n.NotificationManager : #011Handler for msisdn: raw
Nov 10 19:49:35 www2018 mxisd[6972]: .107  INFO [           main]         i.k.m.n.NotificationManager : #011Handler for email: raw
Nov 10 19:49:35 www2018 mxisd[6972]: .171  INFO [           main]   com.j256.ormlite.table.TableUtils : creating table 'invite_3pid'
Nov 10 19:49:35 www2018 mxisd[6972]: .243  INFO [           main]   com.j256.ormlite.table.TableUtils : executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `invite_3pid` (`id` VARCHAR , `token` VARCHAR NOT NULL , `sender` VARCHAR NOT NULL , `medium` VARCHAR NOT NULL , `address` VARCHAR NOT NULL , `roomId` VARCHAR NOT NULL , `properties` VARCHAR , PRIMARY KEY (`id`) )
Nov 10 19:49:35 www2018 mxisd[6972]: .246  INFO [           main]   com.j256.ormlite.table.TableUtils : creating table 'session_3pid'
Nov 10 19:49:35 www2018 mxisd[6972]: .246  INFO [           main]   com.j256.ormlite.table.TableUtils : executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `session_3pid` (`id` VARCHAR , `creationTime` BIGINT NOT NULL , `server` VARCHAR NOT NULL , `medium` VARCHAR NOT NULL , `address` VARCHAR NOT NULL , `secret` VARCHAR NOT NULL , `attempt` INTEGER NOT NULL , `nextLink` VARCHAR , `token` VARCHAR NOT NULL , `validated` BOOLEAN , `validationTime` BIGINT , `isRemote` BOOLEAN NOT NULL , `remoteServer` VARCHAR , `remoteId` VARCHAR , `remoteSecret` VARCHAR , `remoteAttempt` INTEGER , `isRemoteValidated` BOOLEAN NOT NULL , PRIMARY KEY (`id`) )
Nov 10 19:49:35 www2018 mxisd[6972]: .338  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider DnsLookupProvider is enabled: true
Nov 10 19:49:35 www2018 mxisd[6972]: .338  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider ForwarderProvider is enabled: true
Nov 10 19:49:35 www2018 mxisd[6972]: .338  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider SynapseSqlThreePidProvider is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider GenericSqlThreePidProvider is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider RestThreePidProvider is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider MemoryIdentityStore is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider LdapThreePidProvider is enabled: true
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider NetIqLdapThreePidProvider is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider WordpressThreePidProvider is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .339  INFO [           main] l.s.RecursivePriorityLookupStrategy : 3PID Provider GoogleFirebaseProvider is enabled: false
Nov 10 19:49:35 www2018 mxisd[6972]: .341  INFO [           main] l.s.RecursivePriorityLookupStrategy : Found 3 providers
Nov 10 19:49:35 www2018 mxisd[6972]: .342  INFO [           main] l.s.RecursivePriorityLookupStrategy : #011- io.kamax.mxisd.lookup.provider.DnsLookupProvider
Nov 10 19:49:35 www2018 mxisd[6972]: .342  INFO [           main] l.s.RecursivePriorityLookupStrategy : #011- io.kamax.mxisd.lookup.provider.ForwarderProvider
Nov 10 19:49:35 www2018 mxisd[6972]: .342  INFO [           main] l.s.RecursivePriorityLookupStrategy : #011- io.kamax.mxisd.backend.ldap.LdapThreePidProvider
Nov 10 19:49:35 www2018 mxisd[6972]: .343  INFO [           main] l.s.RecursivePriorityLookupStrategy : Recursive lookup enabled: true
Nov 10 19:49:35 www2018 mxisd[6972]: .343  INFO [           main] l.s.RecursivePriorityLookupStrategy : 127.0.0.0/8 is allowed for recursion
Nov 10 19:49:35 www2018 mxisd[6972]: .344  INFO [           main] l.s.RecursivePriorityLookupStrategy : 10.0.0.0/8 is allowed for recursion
Nov 10 19:49:35 www2018 mxisd[6972]: .345  INFO [           main] l.s.RecursivePriorityLookupStrategy : 172.16.0.0/12 is allowed for recursion
Nov 10 19:49:35 www2018 mxisd[6972]: .345  INFO [           main] l.s.RecursivePriorityLookupStrategy : 192.168.0.0/16 is allowed for recursion
Nov 10 19:49:35 www2018 mxisd[6972]: .345  INFO [           main] l.s.RecursivePriorityLookupStrategy : ::1/128 is allowed for recursion
Nov 10 19:49:35 www2018 mxisd[6972]: .409  INFO [           main]  i.k.m.invitation.InvitationManager : Loading saved invites
Nov 10 19:49:35 www2018 mxisd[6972]: .425  INFO [           main]  i.k.m.invitation.InvitationManager : Setting up invitation mapping refresh timer
Nov 10 19:49:35 www2018 mxisd[6972]: .529  INFO [           main]    i.k.m.directory.DirectoryManager : Directory providers:
Nov 10 19:49:35 www2018 mxisd[6972]: .530  INFO [           main]    i.k.m.directory.DirectoryManager : #011- io.kamax.mxisd.backend.ldap.LdapDirectoryProvider
Nov 10 19:49:36 www2018 mxisd[6972]: .556  INFO [           main] k.m.MatrixIdentityServerApplication : Started MatrixIdentityServerApplication in 6.159 seconds (JVM running for 6.645)

**Comment by maxidor** [comment]
Indeed it's not called, you most likely skipped the setup steps in https://github.com/kamax-matrix/mxisd/blob/master/docs/features/authentication.md

**Comment by rsacher** [comment]
Thanks.... I overlooked this step:
https://github.com/kamax-matrix/matrix-synapse-rest-auth
Now it works fine - thank you!

**Comment by maxidor** [comment]
Glad it works!
